#! /bin/sh

# pywal
# wal -R
. "${HOME}/.cache/wal/colors.sh" # Import the colors

# Keyboard shortcuts
pgrep -x sxhkd > /dev/null || sxhkd &

# Input layout
setxkbmap -layout us,se

# Compositor
picom &

# Monitor layout
~/.screenlayout/reset.sh
~/.screenlayout/monitor.sh

# Wallpaper
nitrogen --restore

# Polybar
~/.config/polybar/launch.sh
bspc config top_padding 27 #Polybar height

# Workspace
bspc monitor DP-1 -d 1 2 3 4
bspc monitor HDMI-0 -d 5 6 7 8

# Tile properties
bspc config focused_border_color "#f21b2b"
#bspc config normal_border_color "#00F0F8FF"

bspc config split_ratio          0.60

bspc config border_width         3
bspc config window_gap           20
# bspc config single_monocle       false
bspc config borderless_monocle   true
# bspc config gapless_monocle      false

#bspc config pointer_follows_focus true
bspc config focus_follows_pointer true
# bspc config swallow_first_click   true

#Start/Reset Audio in workspace 4
bspc rule -a QjackCtl desktop=4 state=floating
bspc rule -a Carla2 desktop=4
killall carla && sleep 1 #Kill carla before qjackctl
killall qjackctl && sleep 1
sleep 1 && qjackctl &

#Virtual manager in worlspace 4
bspc rule -a Virt-manager desktop=4
killall virt-manager
sleep 1 && virt-manager &
